### ISSUE TITLE
Interactive note entry

### ISSUE THREAD

**Issue by ThDag** [ThDag/NotesOnly#1]
when creating a note the note data is entered along with the commands but this way the note will be entered after the command is executed with a interactive input section 

Benefits
- cleaner look
- no need to surround with double quote
- better visualization for normal and multi-line notes

**Comment by SchBenedikt** [comment]
Ask chatGPT if he can do it with PyQT5 too. PyQT5 is a tool that allows you to create apps with a graphical interface.

**Comment by ThDag** [comment]
Good idea but when i said interactive section i didn't meant gui its like a input in cli where you can enter your note

I don't really see the benefit of a pop up ui window

whats in your mind

**Comment by SchBenedikt** [comment]
Ah, but that sounds good too. For many, a GUI is simply more appealing than a terminal window.

**Comment by ThDag** [comment]
well i agree gui more appealing but after all its a cli app and app is used in cli, gui is more appealing then cli generally but not when using cli app also there isnt anything for this app that you can do in gui but note in cli its just note entry

**Comment by ThDag** [comment]
the code has been updated to make the addn interactive
